=== GTrunSec/waterwheel/docs/job-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "uuid",
    "project",
    "name",
    "description",
    "triggers",
    "tasks"
  ],
  "properties": {
    "uuid": {
      "type": "string",
      "format": "uuid"
    },
    "project": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "paused": {
      "type": "boolean",
      "default": "false"
    },
    "triggers": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "start"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "start": {
            "type": "string",
            "format": "timestamp"
          },
          "end": {
            "type": "string",
            "format": "timestamp"
          },
          "period": {
            "type": "string"
          },
          "cron": {
            "type": "string"
          }
        }
      }
    },
    "tasks": {
      "type": "array",
      "items":{
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "docker": {
            "type": "object",
            "required": [
              "image",
              "args"
            ],
            "properties": {
              "image": {
                "type": "string"
              },
              "args": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "env": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          },
          "depends": {
            "type": "array",
            "items":{
              "type": "string"
            }
          },
          "depends_failure": {
            "type": "array",
            "items":{
              "type": "string"
            }
          },
          "threshold": {
            "type": "integer"
          }
        }
      }
    }
  }
}

=== GTrunSec/waterwheel/sample/jobs/testedit.json
{
  "uuid": "4ea39920-8bb3-4afd-99d5-ab8f4d871f13",
  "project": "test_project",
  "name": "test_edit",
  "description": "a simple job to test that task edits are broadcast correctly",
  "paused": false,
  "triggers": [
    {
      "name": "every_minute",
      "start": "2021-04-07T00:00:00Z",
      "period": "1m"
    }
  ],
  "tasks": [
    {
      "name": "step0",
      "depends": [
        "trigger/every_minute"
      ]
    }
  ]
}

=== GTrunSec/waterwheel/sample/crash.json
{
  "uuid": "67b56d78-134a-4299-958e-e16e37469145",
  "project": "test_project",
  "name": "test_trigger_crash",
  "description": "possibly causes a crash in the server process",
  "triggers": [
    {
      "name": "trigger_a",
      "start": "2021-02-11T00:00:00Z",
      "period": "1h"
    },
    {
      "name": "trigger_b",
      "start": "2021-02-11T00:20:00Z",
      "period": "1h"
    },
    {
      "name": "trigger_c",
      "start": "2021-02-11T00:40:00Z",
      "period": "1h"
    }
  ],
  "tasks": [
    {
      "name": "step_0",
      "docker": {
        "image": "bash",
        "args": [
          "echo",
          "step 0"
        ]
      },
      "depends": [
        "trigger/trigger_a",
        "trigger/trigger_b",
        "trigger/trigger_c"
      ],
      "threshold": 1
    }
  ]
}
